# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create and set working directory
WORKDIR /app

# Copy package.json (and package-lock.json if available)
COPY package.json ./

# Install dependencies using npm install instead of npm ci as no package-lock.json is available
RUN npm install --ignore-scripts

# Copy tsconfig and source files
COPY tsconfig.json ./
COPY src/ ./src/

# Build the project
RUN npm run build

# Default command to run the MCP server
CMD ["node", "build/index.js"]
